services:
  barber-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: barber-app
    restart: always
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "3005:3000"
    networks:
      - easypanel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.barberapp.rule=Host(`dfautomatic.cloud`,`www.dfautomatic.cloud`) && PathPrefix(`/barber`)"
      - "traefik.http.services.barberapp.loadbalancer.server.port=3000"

networks:
  easypanel:
    external: true
